[window]

#opacity = 0.9

padding.x = 10
padding.y = 10

[font]

size = 13.0

normal      = { family = "JetBrains Mono", style = "Regular" }
bold        = { family = "JetBrains Mono", style = "Regular" }
italic      = { family = "JetBrains Mono", style = "Regular" }
bold_italic = { family = "JetBrains Mono", style = "Regular" }

